# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Update apt package list
      run: sudo apt-get update
      
    - name: Install Chrome and Chrome webdriver for Selenium
      run: |
        sudo apt-get install -yqq \
          chromium-browser chromium-chromedriver

    - name: Install Firefox and Firefox webdriver for Selenium
      run: |
        sudo apt-get install -yqq \
          firefox webkit2gtk-driver \
  
    - name: Install TOX
      run: sudo pip install -U tox

    - name: Start X
      run: nohup startx &
  
    - name: Run tests with tox
      env:
        DISPLAY: ":0"
      run: tox
